### ISSUE TITLE
New Plugin Testing 

### ISSUE THREAD

**Issue by starstuff2020** [mnelson4/printmyblog#66]
Michael - this is wpodeskstar (from wordpress support).  

I wanted to further expand on the testing I did for plugin update.  

I would like to see "Post Selection" added  to "Settings" as well.  That way the print option will be available on front page.  

What would be the ultimate is if I could choose which pages and post for the button to show up.  Something like this possibly:
![printblog1](https://user-images.githubusercontent.com/64659466/80836602-f6870880-8ba9-11ea-931e-3aba3282c9b8.png)

I'm going to be installing the new plugin to more of my sites in the next few days.

Feel free to email me directly.

Peggy

**Comment by mnelson4** [comment]
Hi again Peggy. Yes selecting which posts/pages to add it to is another feature that’s been requested. But I was thinking of adding it as an option onto each post: so you’d write a post, and in the sidebar you would select whether or not it should enablr print buttons. That could support more options per page (eg if you wanted different content or layout per post/page) and it could be more convenient when adding a single new posts/pages; but your suggested approach would be faster when bulk adding the button onto multiple posts/pages all at once... so I think there’s a trade off.
Thoughts on that?

**Comment by starstuff2020** [comment]
I see what you are saying.  In my case - I don’t write a lot of the posts so it would be one more thing for me to train the actual authors and then go back into theIr posts when they forget.  

Personally I would pick bulk over individual.

**Comment by mnelson4** [comment]
Yeah ok. I suppose selecting posts and pages (almost the same "post selection" inputs) would be handy, especially if you could specify certain posts, or maybe even exclude certain posts. (Eg I could see folks wanting to have print buttons on almost all posts and pages, except their homepage and contact page, etc.)

Anyways, I probably won't get around to adding that fully just yet, but I'll add a filter so you can get the same result, you'll just need a code snippet again. I'll let you know when I've added that.

**Comment by starstuff2020** [comment]
I have a document with 207 red check marks (they are images) at the beginning of the line like this:  

![tickcorrect](https://user-images.githubusercontent.com/64659466/81093296-bf20a080-8eb6-11ea-9f45-18ee9a4035ec.png)


But the "pdf" or "print" is taking the image and centering it above the line where it's suppose to display:  

![tickincorrect](https://user-images.githubusercontent.com/64659466/81093453-0313a580-8eb7-11ea-8826-5b95ad8b9a2a.png)

Any fix to this?

**Comment by mnelson4** [comment]
hi @starstuff2020, can you point me to the live page? It's because Print My Blog is treating the checkmark like a big image, and so it's defaulting to centering it and avoiding page breaks in it etc.
Are those checkmarks added by a plugin or what?

**Comment by starstuff2020** [comment]
Hi - no plugin - just images that were placed in front of each line and set to no alignment.

To fix the issue I  replaced all of the checkmark images with special character for tick mark and made them red.  So they are printing/saving correctly and I don't have a "live page" to show you.

**Comment by starstuff2020** [comment]
Michael - I've installed the plugin on another site to test and am having an issue with the buttons not being visible to viewers.  I have tried both the 2.3.6 version and the 2.4 version with the same results.  Each time I go back into the "settings" page the box is not check marked.  Wordpress version is 5.4.1.  

This is a view of my saved settings:

![image](https://user-images.githubusercontent.com/64659466/81338546-adc7c780-9061-11ea-91a6-4fa9fa3537ba.png)

And this is what it looks like if I open the settings again:

![image](https://user-images.githubusercontent.com/64659466/81338229-1febdc80-9061-11ea-9082-3d280b4c00bc.png)

**Comment by mnelson4** [comment]
Hmmmm there was an error in 2.4.0 that was producing some warnings that might have been interfering, which I just fixed in 2.4.1. That might have been the issue; if so upgrading to 2.4.1 should fix it.

**Comment by mnelson4** [comment]
And regardint the checkmarks, I was able to reproduce that problem on my test site -- I just needed to use the classic editor and add a tiny image with no alignment. 
I made another version of the plugin that solved the issue for me: https://github.com/mnelson4/printmyblog/archive/BUG/66/checkmarks.zip
If you'd like to try that version like before that would be good, but no worries if you can't right now.

**Comment by starstuff2020** [comment]
Updated to 2.4.1 - still have the same problem.  The "show visitor buttons" option won't save.  
I also tried alternative theme.

Thanks for the checkmark fix.  If I run into any more of those issues I will definitely use it.

**Comment by mnelson4** [comment]
Hmmm that's very strange that the settings aren't saving. What version of WordPress and PHP is that site on?

**Comment by starstuff2020** [comment]
Wordpress 5.4.1 and php 7.2.  Same as all the other sites I’ve successfully used your plugin on.  So weird.

**Comment by mnelson4** [comment]
Ya that’s all good... heres a long-shot guess: emojis! Can you try changing the print text from the cute emojis to just regular text, and see if it saves them? (A while ago emojis weren’t supported, and it’s possible the database didn’t get updated.)
If that doesn’t fix it, can you share which plugins are active? Or are you familiar with running database queries?

**Comment by starstuff2020** [comment]
I changed the print text in my writing settings:  no change

Here is a list of my active plugins for this site (all updated to latest versions):
Advanced WP Columns
Akismet Anti-Spam
All In One SEO Pack
Automatic Copyright Year
Broken Link Checker
Classic Editor
Comment Images
Display Widgets
Forget About Shortcode Buttons
GTranslate
HeatMap AdAptive Pro Plugin
Limit Login Attempts
Popup Maker
Really Simple SSL
Shortcode in Comment
Supreme Google Webfonts
TablePress
TablePress Extension: Responsive Tables
TinyMCE Advanced
TinyMCE Advanced
Video.js - HTML5 Video Player for WordPress
WP Ultimate Recipe
WP-Columna
WP-SpamShield
WPForms Lite

Database queries:  I'm familiar with phpmyadmin so should be able to figure it out (with a bit of guidance).

**Comment by starstuff2020** [comment]
Hey Michael, When I use "print" button and save as pdf. the video splash screens are getting cut at a page break instead of keeping it together.  

Plugin being used to play videos and display splash screen image is Video.js - HTML5 Video Player for WordPress

![print-version-video400](https://user-images.githubusercontent.com/64659466/81584877-3303f280-9368-11ea-98f2-1ddcee08adbd.gif)

**Comment by mnelson4** [comment]
Ok thanks for the complete list, I'll try the suspicious ones (spam and security ones, mainly).

I'd like to see if the settings are getting set in the database OK or what. 
Could you please

1. Go to the settings page, change a few settings, and take a screenshot of what you changed them to.
2. Click save
3. Go to PHPMyAdmin and run this query `select option_value from wp_options where option_name like 'pmb-print-now-settings'` (assuming the tables start with the default `wp_`. If your tables all start with something different you would need to adjust that)
4. Copy the result in here.

That might provide a clue about what's going wrong.

Regarding the video splash screens, it seems those videos are too big for the screen, and the browser is cutting them in half like that. I'll see what I can do for that one...

**Comment by starstuff2020** [comment]
![1](https://user-images.githubusercontent.com/64659466/81597066-f17c4300-9379-11ea-95e0-946d877d0e4b.jpg)
![2](https://user-images.githubusercontent.com/64659466/81597080-f80aba80-9379-11ea-8e98-cf30057fac2a.jpg)
![3](https://user-images.githubusercontent.com/64659466/81597088-fb9e4180-9379-11ea-807d-5f45115a4147.jpg)
![4](https://user-images.githubusercontent.com/64659466/81597092-fe009b80-9379-11ea-9c0f-0b06b72ddb8e.jpg)

**Here is the text from the query:**

a:4:{s:12:"show_buttons";b:1;s:5:"print";a:3:{s:14:"frontend_label";s:10:"Print ?";s:6:"active";b:1;s:13:"print_options";a:25:{s:14:"rendering_wait";i:200;s:17:"include_inline_js";b:0;s:10:"shortcodes";b:0;s:15:"post_page_break";b:1;s:7:"columns";i:1;s:9:"font_size";s:6:"normal";s:10:"image_size";s:4:"full";s:5:"links";s:7:"include";s:15:"show_site_title";b:1;s:17:"show_site_tagline";b:1;s:13:"show_site_url";b:1;s:12:"show_filters";b:0;s:17:"show_date_printed";b:0;s:11:"show_credit";b:1;s:10:"show_title";b:1;s:7:"show_id";b:0;s:11:"show_author";b:0;s:8:"show_url";b:0;s:9:"show_date";b:0;s:15:"show_categories";b:0;s:19:"show_featured_image";b:1;s:12:"show_excerpt";b:0;s:12:"show_content";b:1;s:13:"show_comments";b:1;s:12:"show_divider";b:0;}}s:3:"pdf";a:3:{s:14:"frontend_label";s:8:"PDF ?";s:6:"active";b:0;s:13:"print_options";a:25:{s:14:"rendering_wait";i:200;s:17:"include_inline_js";b:0;s:10:"shortcodes";b:0;s:15:"post_page_break";b:1;s:7:"columns";i:1;s:9:"font_size";s:6:"normal";s:10:"image_size";s:6:"medium";s:5:"links";s:7:"include";s:15:"show_site_title";b:1;s:17:"show_site_tagline";b:1;s:13:"show_site_url";b:1;s:12:"show_filters";b:1;s:17:"show_date_printed";b:1;s:11:"show_credit";b:1;s:10:"show_title";b:1;s:7:"show_id";b:0;s:11:"show_author";b:0;s:8:"show_url";b:0;s:9:"show_date";b:1;s:15:"show_categories";b:1;s:19:"show_featured_image";b:1;s:12:"show_excerpt";b:0;s:12:"show_content";b:1;s:13:"show_comments";b:0;s:12:"show_divider";b:0;}}s:5:"ebook";a:3:{s:14:"frontend_label";s:10:"eBook ?";s:6:"active";b:0;s:13:"print_options";a:25:{s:14:"rendering_wait";i:200;s:17:"include_inline_js";b:0;s:10:"shortcodes";b:0;s:15:"post_page_break";b:1;s:7:"columns";i:1;s:9:"font_size";s:6:"normal";s:10:"image_size";s:6:"medium";s:5:"links";s:7:"include";s:15:"show_site_title";b:1;s:17:"show_site_tagline";b:1;s:13:"show_site_url";b:1;s:12:"show_filters";b:1;s:17:"show_date_printed";b:1;s:11:"show_credit";b:1;s:10:"show_title";b:1;s:7:"show_id";b:0;s:11:"show_author";b:0;s:8:"show_url";b:0;s:9:"show_date";b:1;s:15:"show_categories";b:1;s:19:"show_featured_image";b:1;s:12:"show_excerpt";b:0;s:12:"show_content";b:1;s:13:"show_comments";b:0;s:12:"show_divider";b:0;}}}

**Comment by mnelson4** [comment]
Ok thanks, so it seems the settings are getting saved to the database ok.
Can you take a screenshot of the settings page when you visit it now, and please expand the print settings area. And just checking: despite whatever you see on the settings page, do you see the print button on posts?

**Comment by mnelson4** [comment]
Ok thanks, it seems the settings are getting saved to the database OK. Then it seems somehow they're just not getting retrieved OK from the database, or getting overwritten immediately. 
I'm sorry I think in order to make more progress on this issue I'd need to see it happening and have access to modify the code. Do you have a test site where this is happening that you could grant me access to?

**Comment by starstuff2020** [comment]
Here is what is showing now:

![5](https://user-images.githubusercontent.com/64659466/81608843-c3076380-938b-11ea-96d0-ae475a7353bf.jpg)
![6](https://user-images.githubusercontent.com/64659466/81608867-cbf83500-938b-11ea-8941-0ccc52cd373d.jpg)
![7](https://user-images.githubusercontent.com/64659466/81609141-314c2600-938c-11ea-86b5-c6f94d3102f3.jpg)


No the button are now showing on any of posts.

**Comment by mnelson4** [comment]
Hmmm that's really strange, especially how it's not even using the default settings. It's like the values are getting overridden.

Last suggestion: Have you tried resetting the values to the default?

I'm sorry I think in order to make more progress on this issue I'd need to see it happening and have access to modify the code and database. Do you have a test site where this is happening that you could grant me access to?

**Comment by starstuff2020** [comment]
Ok - so the settings not saving is obviously something with just this one website.  The plugin worked  beautifully on the 3 other sites I used it on.  I don't want to take any more of your time for this issue.  I will download all the posts all and break them up with adobe.  

Here is the code for the video that is getting sliced:
[videojs mp4="https://www.numberu.com/video/KingDavidsSignature.mp4" poster="https://goyimgazette.com/wp-content/uploads/KingDavidSplash.png" width="1280" height="720" class="aligncenter"]

**Comment by mnelson4** [comment]
> The plugin worked beautifully on the 3 other sites I used it on. I don't want to take any more of your time for this issue.

I'm really sorry we coudln't figure it out.

I'll look into the videojs issue asap (FYI I created a separate GitHub issue specifically for it: https://github.com/mnelson4/printmyblog/issues/69).

**Comment by mnelson4** [comment]
Huh, the videoJS I found is slightly different: [I got it off wp.org](https://wordpress.org/plugins/videojs-html5-player/); the shortcode it expects starts with `videojs_video` and other differences. Are you using the same plugin, version 1.1.3?

Anyways, I stayed up kinda crazy late seeing if I could fix the issue. Could you try [downloading the upcoming version, 2.4.2](https://github.com/mnelson4/printmyblog/archive/BUG/66/checkmarks.zip) and using it on the site with the problem? If that doesn't resolve it, can you share a link to the URL of the print-page where you're having the issue? Also, which browser are you using?

But hopefully, that next version fixes it 🤞 (it seemed to for me).

**Comment by starstuff2020** [comment]
Hey Night Owl!

Here is the link to the plugin (sorry should have provided that before) https://wordpress.org/plugins/videojs-html5-video-player-for-wordpress/ 

I have the latest version installed but I see there is a notice that the plugin hasn't been tested with my version of wordpress.  I haven't noticed any issues (but maybe that is the problem?)

I am seeing the issue on PAGES when I use the "print now" feature from admin dashboard.  For example:  https://betterness.com - the home page has lots of videos that get cut off.  

Ok - I have copied all the page code from betterness.com home page to a post https://betterness.com/plugintest and turned on all 3 buttons for you to test with.  (Please let me know when you are done so I can delete it.)

Here is a screenshot of chrome settings I used:

![image](https://user-images.githubusercontent.com/64659466/81836466-5eb5e280-94f8-11ea-8405-d9bc6e5fa553.png)


That being said:  The videos don't play anyway (not in print or pdf mode) so  it's not a super big deal.  In my case I am just editing them in adobe to make them look correct and then uploading the edited file to the server for users to download directly.  (mostly because I don't understand how this plugin works on mobile devices - but that is different subject).

**Comment by mnelson4** [comment]
> Here is the link to the plugin (sorry should have provided that before) wordpress.org/plugins/videojs-html5-video-player-for-wordpress

D'oh! I should have double-checked that too. Ah well, I'll know to ask for a link next time rather than looking it up.

> I have the latest version installed but I see there is a notice that the plugin hasn't been tested with my version of wordpress. I haven't noticed any issues (but maybe that is the problem?)

I got a warning when I activated it, so it's getting a bit dated. But I turned off debugging mode on my site and it worked fine.

> I am seeing the issue on PAGES when I use the "print now" feature from admin dashboard. For example: betterness.com - the home page has lots of videos that get cut off.

Ok yes I see the issue happening often in Google Chrome (but not in Firefox). I updated the [version 2.4.2 to try to fix that. Please try that version on your site.](https://github.com/mnelson4/printmyblog/archive/BUG/66/checkmarks.zip)

Also, I noticed you have a large image with text in front of it on one page that says "If you don't come out of quaratine with...." and because its so tall its often getting cut in half. If you'd like to avoid that, you can add the class `pmb-no-break` on it (that tells the browser to avoid a page-break inside it, although the browser can ignore that.)

**Comment by mnelson4** [comment]
FYI someone else is getting the issue where the settings aren't saving 😖: https://github.com/mnelson4/printmyblog/issues/71

**Comment by starstuff2020** [comment]
I have updated my version to 2.4.2.

You are right about Firefox showing different results.  No more video splash screen being cut off because they are completely gone.  

I’m glad someone else is having the “save settings”  problem.  Hopefully with that input you can pinpoint the problem (and I’m officially not crazy :)

**Comment by mnelson4** [comment]
Ok I've released 2.4.2 as the other person was reporting it was helping them. Maybe you were using an older zip (before the fix got added)? ie, if you try the released version, 2.4.2, it should be fixed. If it's not, please mention it on https://github.com/mnelson4/printmyblog/issues/71.

So @starstuff2020 I'm going to close this issue, but if you have other problems/suggestions please create new issues in GitHub for each one. That just helps keep this organized.
